/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'street' : string,
  'city' : string,
  'postalCode' : string,
  'number' : bigint,
}
export interface CalculatorLead {
  'qualityTier' : string,
  'projectType' : string,
  'name' : string,
  'address' : Address,
  'mobile' : string,
  'areaInSqFt' : number,
  'numFloors' : bigint,
}
export interface ContactForm {
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface EstimateResponse {
  'breakdown' : string,
  'estimatedCost' : bigint,
}
export interface QueryForm {
  'serviceType' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateEstimate' : ActorMethod<
    [
      string,
      string,
      string,
      number,
      bigint,
      string,
      string,
      bigint,
      string,
      string,
    ],
    EstimateResponse
  >,
  'getAllCalculatorLeads' : ActorMethod<[], Array<CalculatorLead>>,
  'getAllContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getAllQueryForms' : ActorMethod<[], Array<QueryForm>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitQueryForm' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];