/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EstimateResponse = IDL.Record({
  'breakdown' : IDL.Text,
  'estimatedCost' : IDL.Nat,
});
export const Address = IDL.Record({
  'street' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'number' : IDL.Nat,
});
export const CalculatorLead = IDL.Record({
  'qualityTier' : IDL.Text,
  'projectType' : IDL.Text,
  'name' : IDL.Text,
  'address' : Address,
  'mobile' : IDL.Text,
  'areaInSqFt' : IDL.Float64,
  'numFloors' : IDL.Nat,
});
export const QueryForm = IDL.Record({
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateEstimate' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [EstimateResponse],
      [],
    ),
  'getAllCalculatorLeads' : IDL.Func([], [IDL.Vec(CalculatorLead)], ['query']),
  'getAllQueryForms' : IDL.Func([], [IDL.Vec(QueryForm)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQueryForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EstimateResponse = IDL.Record({
    'breakdown' : IDL.Text,
    'estimatedCost' : IDL.Nat,
  });
  const Address = IDL.Record({
    'street' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'number' : IDL.Nat,
  });
  const CalculatorLead = IDL.Record({
    'qualityTier' : IDL.Text,
    'projectType' : IDL.Text,
    'name' : IDL.Text,
    'address' : Address,
    'mobile' : IDL.Text,
    'areaInSqFt' : IDL.Float64,
    'numFloors' : IDL.Nat,
  });
  const QueryForm = IDL.Record({
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateEstimate' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [EstimateResponse],
        [],
      ),
    'getAllCalculatorLeads' : IDL.Func(
        [],
        [IDL.Vec(CalculatorLead)],
        ['query'],
      ),
    'getAllQueryForms' : IDL.Func([], [IDL.Vec(QueryForm)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQueryForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };